config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'wallets#index'

  resources :users, only: %i(new create)
  resources :teams, only: %i(new create)
  resources :stocks, only: %i(new create)
  resources :wallets, only: %i(index new create)
  resources :transactions, only: %i(index new create)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_one :wallet, as: :wallatable
  validates :name, presence: true

  after_create { create_wallet }
end

app/models/team.rb
class Team < ApplicationRecord
  has_one :wallet, as: :wallatable
  validates :name, presence: true

  after_create { create_wallet }
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  has_one :source, class_name: 'Wallet', foreign_key: :id, primary_key: :source_id
  has_one :target, class_name: 'Wallet', foreign_key: :id, primary_key: :target_id

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validate :amount_less_or_equal_than_actual_blance

  def kind
    return 'deposit' if source.nil?
    return 'withdraw' if target.nil?
    'transfer'
  end

  def amount_less_or_equal_than_actual_blance
    if source && amount.present? && (source.balance < amount)
      errors.add :amount, 'should be minor or equal to source wallet actual balance'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :wallet, as: :wallatable
  validates :name, presence: true

  after_create { create_wallet }
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  belongs_to :wallatable, polymorphic: true, optional: true
  has_many :source_transactions, class_name: 'Transaction', foreign_key: :source_id
  has_many :target_transactions, class_name: 'Transaction', foreign_key: :target_id

  def to_s
    "#{wallatable.name} (##{id})"
  end

  def balance
    balance_until Time.now
  end

  def balance_until(time)
    return 0 unless target_transactions.any?
    target_transactions.where('created_at <= ?', time).pluck(:amount).sum -
        source_transactions.where('created_at <= ?', time).pluck(:amount).sum
  end

  def deposit(amount)
    target_transactions.create amount: amount
  end

  def withdraw(amount)
    source_transactions.create amount: amount
  end

  def transfer_to(wallet, amount:)
    source_transactions.create amount: amount, target_id: wallet.id
  end

  def transactions
    Transaction.where('source_id = :id OR target_id = :id', id: id).order('created_at desc')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def save_and_render_owner
    if @owner.save
      @wallets = Wallet.all
      flash.now[:notice] = 'Owner was successfully created.'
      render partial: 'wallets/index'
    else
      render partial: 'layouts/owner_form', status: :unprocessable_entity
    end
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def create
    @owner = Stock.new(user_params)
    save_and_render_owner
  end

  private
  def user_params
    params.require(:stock).permit(:name)
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def create
    @owner = Team.new(user_params)
    save_and_render_owner
  end

  private
  def user_params
    params.require(:team).permit(:name)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @wallet = Wallet.find params[:wallet_id]
    @transactions = @wallet.transactions
    render partial: 'index'
  end

  def new
    @transaction = Transaction.new
    @kind = params[:kind]
    render partial: 'form'
  end

  def create
    @transaction = Transaction.new(user_params)
    if @transaction.save
      @wallets = Wallet.all
      flash.now[:notice] = "#{@transaction.kind.capitalize} was successfully created."
      render partial: 'wallets/index'
    else
      @kind = @transaction.kind
      render partial: 'form', status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:transaction).permit(:source_id, :target_id, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @owner = User.new(user_params)
    save_and_render_owner
  end

  private
  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  def index
    @wallets = Wallet.all
  end

  def new
    @owner = params[:owner_type].constantize.new
    render partial: 'layouts/owner_form'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash_messages.haml
- if notice
  .alert.alert-info
    = notice
    %button.close{data: {dismiss: "alert"}} ×
- if alert
  .alert.alert-danger
    = alert
    %button.close{data: {dismiss: "alert"}} ×

app/views/layouts/_form_errors.haml
= form.error_notification
- if form.object.errors[:base].present?
  = form.error_notification message: form.object.errors[:base].to_sentence
  

app/views/layouts/_owner_form.html.haml
.modal-header
  %h5.modal-title New Owner
  %button.close{data: {dismiss: "modal"}} ×

= simple_form_for @owner, data: {action:'ajax:complete->wallets#submit'}, remote: true do |f|
  .modal-body
    = render partial: 'layouts/form_errors', locals: { form: f }

    .form-inputs
      = f.input :name

  .modal-footer
    %button.btn.btn-secondary{data: {dismiss: "modal"}, type: "button"} Close
    = f.submit 'Save', class: 'btn btn-primary'

app/views/layouts/_topbar.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{href: '/'} Wallet System
  %button.navbar-toggler{aria: {controls: "navbarNav", expanded: "false", label: "Toggle navigation"}, data: {target: "#navbarNav", toggle: "collapse"}, type: "button"}
    %span.navbar-toggler-icon
  #navbarNav.collapse.navbar-collapse
    %ul.navbar-nav.ml-auto
      %li.nav-item
        = link_to wallets_path, class: 'nav-link', title: 'Wallets list' do
          %i.fa.fa-lg.fa-money

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wallet
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: 'layouts/topbar'
    = render partial: 'layouts/flash_messages'

    .container= yield

app/views/transactions/_form.html.haml
.modal-header
  %h5.modal-title New #{@kind.capitalize}
  %button.close{data: {dismiss: "modal"}} ×

= simple_form_for @transaction, data: {action:'ajax:complete->wallets#submit'}, remote: true do |f|
  .modal-body
    = render partial: 'layouts/form_errors', locals: { form: f }

    .form-inputs
      = f.input :source_id, input_html: { value: params[:source_id] || @transaction.source_id }, as: :hidden
      - if @kind == 'transfer'
        = f.input :target_id, collection: Wallet.all, value_method: :id, include_blank: false
      - else
        = f.input :target_id, input_html: { value: params[:target_id] || @transaction.target_id }, as: :hidden
      = f.input :amount

  .modal-footer
    %button.btn.btn-secondary{data: {dismiss: "modal"}, type: "button"} Close
    = f.submit 'Save', class: 'btn btn-primary'

app/views/transactions/_index.haml
.modal-header
  %h3 Balance: #{@wallet.balance}
  %button.close{data: {dismiss: "modal"}} ×

.modal-body
  - if @transactions.any?
    %table.table.table-striped.table-sm
      %thead
        %tr
          %th Time
          %th Type
          %th Source
          %th Target
          %th Amount
          %th Balance

      %tbody
        - @transactions.each do |t|
          %tr{data: {id: t.id}}
            %td #{time_ago_in_words t.created_at, include_seconds: true} ago
            %td= t.kind.capitalize
            %td= t.source
            %td= t.target
            %td= t.amount
            %td= @wallet.balance_until t.created_at

app/views/wallets/_index.haml
= render partial: 'layouts/flash_messages'
- if @wallets.any?
  %table.table.table-striped.table-sm
    %thead
      %tr
        %th Owner
        %th Type
        %th Balance
        %th

    %tbody
      - @wallets.each do |wallet|
        %tr{data: {id: wallet.id}}
          %td= wallet.wallatable.name
          %td= wallet.wallatable_type
          %td= wallet.balance
          %td
            = link_to new_transaction_path(kind: 'deposit', target_id: wallet.id), class: 'btn btn-primary btn-sm mr-1', title: 'Deposit', data: { action:'wallets#show' }, remote: true do
              %i.fa.fa-lg.fa-sign-in
            = link_to new_transaction_path(kind: 'transfer', source_id: wallet.id), class: 'btn btn-info btn-sm mr-1', title: 'Transfer', data: { action:'wallets#show' }, remote: true do
              %i.fa.fa-lg.fa-exchange
            = link_to new_transaction_path(kind: 'withdraw', source_id: wallet.id), class: 'btn btn-danger btn-sm mr-1', title: 'Withdraw', data: { action:'wallets#show' }, remote: true do
              %i.fa.fa-lg.fa-sign-out
            - if wallet.target_transactions.any?
              = link_to transactions_path(wallet_id: wallet.id), class: 'btn btn-primary btn-sm mr-1', title: 'History', data: { action:'wallets#show' }, remote: true do
                %i.fa.fa-lg.fa-eye

app/views/wallets/index.haml
#wallets{data:{controller: 'wallets'}}
  = link_to 'New User', new_wallet_path(owner_type: 'User'), class: 'btn btn-primary mb-2 mt-2', data:{action:'wallets#show'}
  = link_to 'New Team', new_wallet_path(owner_type: 'Team'), class: 'btn btn-primary mb-2 mt-2', data:{action:'wallets#show'}
  = link_to 'New Stock', new_wallet_path(owner_type: 'Stock'), class: 'btn btn-primary mb-2 mt-2', data:{action:'wallets#show'}

  #index{data:{target: 'wallets.index'}}= render partial: 'index'

  #formModal.modal.fade
    .modal-dialog
      .modal-content{data:{target: 'wallets.modalContent'}}